"""Performance analysis module for the Metaculus forecasting bot.

Collects resolved question data from the Metaculus API, scores predictions,
and provides reusable analysis functions.
"""

from metaculus_bot.performance_analysis.analysis import (
    binary_summary,
    declared_percentile_pit,
    disagreement_predicts_error,
    financial_vs_nonfinancial_pit,
    generate_report,
    max_step_clamp_screen,
    mc_summary,
    no_bias_check,
    numeric_pit_analysis,
    per_model_binary_scores,
    per_model_cohort,
    platform_score_summary,
    stacking_effectiveness,
)
from metaculus_bot.performance_analysis.audit import (
    emit_combined_report,
    emit_external_comment_stub,
    emit_miss_markdown,
    emit_synthesis,
    load_combined_dataset,
    rank_our_models_by_accuracy,
    ranking_caveats,
    select_cohort,
    select_worst_misses,
)
from metaculus_bot.performance_analysis.collector import (
    build_performance_dataset,
    fetch_bot_comments,
    fetch_resolved_questions,
    load_dataset,
    rescore_records,
    save_dataset,
)
from metaculus_bot.performance_analysis.parsing import (
    MIN_SCOREABLE_ANCHORS,
    annotate_forecaster_bullets_with_models,
    anonymous_model_key,
    declared_anchors,
    detect_historical_stacker_signature,
    extract_model_display_name_from_reasoning,
    is_anonymous_model_key,
    parse_forecaster_model_map,
    parse_inferred_stacker_outcome,
    parse_per_model_forecasts,
    parse_per_model_numeric_percentiles,
    parse_per_model_reasoning_text,
    parse_resolution,
    parse_stacked_marker,
    parse_stacker_outcome_marker,
    parse_stacker_skip_reason_marker,
)
from metaculus_bot.performance_analysis.platform_scores import (
    PEER_FIELD,
    SPOT_PEER_FIELD,
    RankingScore,
    peer_score,
    platform_score_fragments,
    ranking_score,
    spot_peer_score,
)
from metaculus_bot.performance_analysis.ranking_cohort import (
    PerModelRankingCohort,
    log_ranking_cohort,
    per_model_ranking_cohort,
)
from metaculus_bot.performance_analysis.research_tags import (
    attach_research_tags,
    research_tags_for_qid,
    research_tags_for_record,
)
from metaculus_bot.performance_analysis.scoring import (
    binary_log_score,
    brier_score,
    mc_log_score,
    numeric_log_score,
)
from metaculus_bot.performance_analysis.stacker_detection import (
    DetectorVerdict,
    compute_production_vs_median_delta,
    detect_stacker_fired,
    exceeded_spread_threshold,
    get_stacker_outcome_field,
    has_stacker_body_marker,
    has_was_stacked_flag,
)

# The standing scoring-exclusion cohorts, re-exported so a round script can reach them
# without knowing they live in the width monitor — retyping the ids is what the constants
# exist to stop.
from metaculus_bot.performance_analysis.width_monitor import (
    DEGRADED_RUN_QIDS,
    EXCLUSION_COHORTS,
    KNOWN_BUG_QIDS,
    PARTIAL_DEGRADED_QIDS,
    parse_exclude_qids,
)

__all__ = [
    "DEGRADED_RUN_QIDS",
    "EXCLUSION_COHORTS",
    "KNOWN_BUG_QIDS",
    "MIN_SCOREABLE_ANCHORS",
    "PARTIAL_DEGRADED_QIDS",
    "PEER_FIELD",
    "SPOT_PEER_FIELD",
    "DetectorVerdict",
    "PerModelRankingCohort",
    "RankingScore",
    "annotate_forecaster_bullets_with_models",
    "anonymous_model_key",
    "attach_research_tags",
    "binary_log_score",
    "binary_summary",
    "brier_score",
    "build_performance_dataset",
    "compute_production_vs_median_delta",
    "declared_anchors",
    "declared_percentile_pit",
    "detect_historical_stacker_signature",
    "detect_stacker_fired",
    "disagreement_predicts_error",
    "emit_combined_report",
    "emit_external_comment_stub",
    "emit_miss_markdown",
    "emit_synthesis",
    "exceeded_spread_threshold",
    "extract_model_display_name_from_reasoning",
    "fetch_bot_comments",
    "fetch_resolved_questions",
    "financial_vs_nonfinancial_pit",
    "generate_report",
    "get_stacker_outcome_field",
    "has_stacker_body_marker",
    "has_was_stacked_flag",
    "is_anonymous_model_key",
    "load_combined_dataset",
    "load_dataset",
    "log_ranking_cohort",
    "max_step_clamp_screen",
    "mc_log_score",
    "mc_summary",
    "no_bias_check",
    "numeric_log_score",
    "numeric_pit_analysis",
    "parse_exclude_qids",
    "parse_forecaster_model_map",
    "parse_inferred_stacker_outcome",
    "parse_per_model_forecasts",
    "parse_per_model_numeric_percentiles",
    "parse_per_model_reasoning_text",
    "parse_resolution",
    "parse_stacked_marker",
    "parse_stacker_outcome_marker",
    "parse_stacker_skip_reason_marker",
    "peer_score",
    "per_model_binary_scores",
    "per_model_cohort",
    "per_model_ranking_cohort",
    "platform_score_fragments",
    "platform_score_summary",
    "rank_our_models_by_accuracy",
    "ranking_caveats",
    "ranking_score",
    "rescore_records",
    "research_tags_for_qid",
    "research_tags_for_record",
    "save_dataset",
    "select_cohort",
    "select_worst_misses",
    "spot_peer_score",
    "stacking_effectiveness",
]
