name: Forecast on Metaculus Cup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */2 * *" # runs at midnight every 2 days

# Add concurrency group to prevent parallel runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false


# Daily job to run the simple forecast bot
jobs:
  forecast_job:
    runs-on: ubuntu-latest # determines the machine that will run the job - keep as is
    steps: # sets up the steps that will be run in order
      # setup repository with all necessary dependencies - keep as is
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: snok/install-poetry@v1
        continue-on-error: true
        with:
          version: 1.8.4
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Ensure Poetry is available (fallback install)
        run: |
          poetry --version || (
            python -m pip install -U pip &&
            for i in 1 2 3; do
              python -m pip install "poetry==1.8.4" && break || sleep 10;
            done &&
            poetry --version
          )
      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 10
          command: poetry install --no-interaction --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: true
          POETRY_VIRTUALENVS_IN_PROJECT: true
          POETRY_INSTALLER_PARALLEL: true
      - name: Run bot
        run: |
          poetry run python main.py --mode metaculus_cup
        # this reads the environment variables from the github repository.
        # Store under Settings --> Secrets and variables --> Actions
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }} # replace this with the name of the variable under which you stored your own Metaculus token
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OAI_ANTH_OPENROUTER_KEY: ${{ secrets.OAI_ANTH_OPENROUTER_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          ASKNEWS_MAX_CONCURRENCY: '1'
          ASKNEWS_MAX_RPS: '0.2'
